
[project]
name = "diplomacy-cli"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
dev = [
	"ruff",
	"pyright",
	"pytest",
	"jsonschema"
]

[tool.ruff]
line-length	= 100
target-version	= "py312"
lint.select	= ["E", "F", "I", "UP"]
