package pipeline

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// AlertManager handles performance regression alerts
type AlertManager struct {
	config      AlertConfig
	projectRoot string
	alertsFile  string
}

// AlertConfig defines alert configuration
type AlertConfig struct {
	Enabled              bool                  `json:"enabled"`
	NotificationChannels []NotificationChannel `json:"notification_channels"`
	AlertThresholds      AlertThresholds       `json:"alert_thresholds"`
	RateLimiting         RateLimitConfig       `json:"rate_limiting"`
	Templates            AlertTemplates        `json:"templates"`
}

// NotificationChannel defines where alerts should be sent
type NotificationChannel struct {
	Type     string            `json:"type"` // "github", "slack", "email", "webhook"
	Enabled  bool              `json:"enabled"`
	Config   map[string]string `json:"config"`   // Channel-specific configuration
	Priority []string          `json:"priority"` // Which alert severities to send
}

// AlertThresholds defines when to trigger alerts
type AlertThresholds struct {
	MinorDegradation    bool `json:"minor_degradation"`
	MajorDegradation    bool `json:"major_degradation"`
	CriticalDegradation bool `json:"critical_degradation"`
	HighVariance        bool `json:"high_variance"`
	TrendDegradation    bool `json:"trend_degradation"`
}

// RateLimitConfig prevents alert spam
type RateLimitConfig struct {
	MaxAlertsPerHour int           `json:"max_alerts_per_hour"`
	CooldownPeriod   time.Duration `json:"cooldown_period"`
	DuplicateWindow  time.Duration `json:"duplicate_window"`
	SuppressRepeated bool          `json:"suppress_repeated"`
}

// AlertTemplates defines message templates
type AlertTemplates struct {
	PerformanceRegression string `json:"performance_regression"`
	HighVariance          string `json:"high_variance"`
	TrendDegradation      string `json:"trend_degradation"`
	Summary               string `json:"summary"`
}

// AlertHistory tracks sent alerts for rate limiting
type AlertHistory struct {
	Alerts []SentAlert `json:"alerts"`
}

// SentAlert represents a previously sent alert
type SentAlert struct {
	ID        string    `json:"id"`
	Type      string    `json:"type"`
	Severity  string    `json:"severity"`
	Benchmark string    `json:"benchmark"`
	Timestamp time.Time `json:"timestamp"`
	Hash      string    `json:"hash"` // For duplicate detection
}

// DefaultAlertConfig returns sensible defaults
func DefaultAlertConfig() AlertConfig {
	return AlertConfig{
		Enabled: true,
		NotificationChannels: []NotificationChannel{
			{
				Type:     "github",
				Enabled:  true,
				Priority: []string{"major", "critical"},
				Config: map[string]string{
					"create_issues": "true",
					"label_prefix":  "performance",
				},
			},
		},
		AlertThresholds: AlertThresholds{
			MinorDegradation:    false,
			MajorDegradation:    true,
			CriticalDegradation: true,
			HighVariance:        true,
			TrendDegradation:    true,
		},
		RateLimiting: RateLimitConfig{
			MaxAlertsPerHour: 10,
			CooldownPeriod:   30 * time.Minute,
			DuplicateWindow:  24 * time.Hour,
			SuppressRepeated: true,
		},
		Templates: AlertTemplates{
			PerformanceRegression: `🚨 Performance Regression Detected

**Benchmark:** {{.BenchmarkName}}
**Severity:** {{.Severity}}
**Performance Impact:** {{.PerformanceChange}}
**Baseline:** {{.BaselineNsPerOp}}ns/op
**Current:** {{.CurrentNsPerOp}}ns/op

{{if .IsCriticalBenchmark}}⚠️ This is a **critical benchmark** that requires immediate attention.{{end}}

**Details:**
- Allocations: {{.AllocChange}}
- Memory: {{.MemoryChange}}
- Statistical Significance: {{.StatisticalSignificance}}

**Next Steps:**
1. Review the performance report for detailed analysis
2. Identify the root cause of the regression
3. Implement performance fixes
4. Re-run benchmarks to validate improvements

---
*Generated by Performance Regression Testing at {{.Timestamp}}*`,

			HighVariance: `⚠️ High Performance Variance Detected

**Benchmark:** {{.BenchmarkName}}
**Variance:** {{.Variance}}%
**Standard Deviation:** {{.StandardDeviation}}

High variance indicates unstable performance that may affect reliability.

**Recommended Actions:**
1. Review test environment for external factors
2. Increase benchmark sample size
3. Check for resource contention
4. Consider performance stabilization measures`,

			TrendDegradation: `📉 Performance Degradation Trend Detected

**Benchmark:** {{.BenchmarkName}}
**Trend Strength:** {{.TrendStrength}}
**Direction:** {{.TrendDirection}}

A consistent degradation trend has been detected over recent runs.

**Analysis:**
- Data Points: {{.DataPointCount}}
- Mean Performance: {{.MeanPerformance}}
- Trend Correlation: {{.TrendCorrelation}}

**Recommended Actions:**
1. Investigate recent changes that may impact performance
2. Review performance optimization opportunities
3. Consider setting up more frequent monitoring`,

			Summary: `📊 Performance Regression Summary

**Total Benchmarks:** {{.TotalBenchmarks}}
**Regressions Detected:** {{.TotalRegressions}}
- Critical: {{.CriticalRegressions}}
- Major: {{.MajorRegressions}}
- Minor: {{.MinorRegressions}}

**High Variance Benchmarks:** {{.HighVarianceBenchmarks}}
**Alerts Generated:** {{.AlertsGenerated}}

{{if .CriticalRegressions}}🚨 **Immediate attention required** for {{.CriticalRegressions}} critical regression(s).{{end}}

View detailed report: {{.ReportURL}}`,
		},
	}
}

// NewAlertManager creates a new alert manager
func NewAlertManager(projectRoot string, config AlertConfig) *AlertManager {
	alertsFile := filepath.Join(projectRoot, "benchmarks", "alerts", "history.json")

	// Ensure alerts directory exists
	os.MkdirAll(filepath.Dir(alertsFile), 0755)

	return &AlertManager{
		config:      config,
		projectRoot: projectRoot,
		alertsFile:  alertsFile,
	}
}

// ProcessAlerts processes regression analysis and sends appropriate alerts
func (am *AlertManager) ProcessAlerts(analysis *RegressionAnalysis) error {
	if !am.config.Enabled {
		return nil
	}

	// Load alert history for rate limiting
	history, err := am.loadAlertHistory()
	if err != nil {
		history = &AlertHistory{Alerts: make([]SentAlert, 0)}
	}

	// Process individual alerts
	for _, alert := range analysis.Alerts {
		if am.shouldSendAlert(alert, history) {
			if err := am.sendAlert(alert, analysis); err != nil {
				fmt.Printf("Failed to send alert: %v\n", err)
				continue
			}

			// Record sent alert
			sentAlert := SentAlert{
				ID:        am.generateAlertID(alert),
				Type:      alert.Type,
				Severity:  alert.Severity,
				Benchmark: alert.BenchmarkName,
				Timestamp: time.Now(),
				Hash:      am.calculateAlertHash(alert),
			}
			history.Alerts = append(history.Alerts, sentAlert)
		}
	}

	// Send summary alert if there are significant regressions
	if am.shouldSendSummaryAlert(analysis) {
		if err := am.sendSummaryAlert(analysis); err != nil {
			fmt.Printf("Failed to send summary alert: %v\n", err)
		}
	}

	// Clean up old alerts and save history
	am.cleanupAlertHistory(history)
	return am.saveAlertHistory(history)
}

// shouldSendAlert determines if an alert should be sent based on configuration and rate limiting
func (am *AlertManager) shouldSendAlert(alert RegressionAlert, history *AlertHistory) bool {
	// Check if alert type is enabled
	switch alert.Type {
	case "performance":
		switch alert.Severity {
		case "minor":
			if !am.config.AlertThresholds.MinorDegradation {
				return false
			}
		case "major":
			if !am.config.AlertThresholds.MajorDegradation {
				return false
			}
		case "critical":
			if !am.config.AlertThresholds.CriticalDegradation {
				return false
			}
		}
	case "variance":
		if !am.config.AlertThresholds.HighVariance {
			return false
		}
	case "trend":
		if !am.config.AlertThresholds.TrendDegradation {
			return false
		}
	}

	// Check rate limiting
	if am.isRateLimited(history) {
		return false
	}

	// Check for duplicate alerts
	if am.config.RateLimiting.SuppressRepeated {
		alertHash := am.calculateAlertHash(alert)
		cutoff := time.Now().Add(-am.config.RateLimiting.DuplicateWindow)

		for _, sent := range history.Alerts {
			if sent.Hash == alertHash && sent.Timestamp.After(cutoff) {
				return false // Duplicate alert within window
			}
		}
	}

	return true
}

// shouldSendSummaryAlert determines if a summary alert should be sent
func (am *AlertManager) shouldSendSummaryAlert(analysis *RegressionAnalysis) bool {
	return analysis.Summary.CriticalRegressions > 0 ||
		analysis.Summary.MajorRegressions > 2 ||
		analysis.Summary.AlertsGenerated > 5
}

// sendAlert sends an individual alert through configured channels
func (am *AlertManager) sendAlert(alert RegressionAlert, analysis *RegressionAnalysis) error {
	for _, channel := range am.config.NotificationChannels {
		if !channel.Enabled {
			continue
		}

		// Check if this channel should receive this severity
		shouldSend := false
		for _, priority := range channel.Priority {
			if priority == alert.Severity {
				shouldSend = true
				break
			}
		}

		if !shouldSend {
			continue
		}

		switch channel.Type {
		case "github":
			err := am.sendGitHubAlert(alert, analysis, channel)
			if err != nil {
				return fmt.Errorf("GitHub alert failed: %v", err)
			}
		case "slack":
			err := am.sendSlackAlert(alert, analysis, channel)
			if err != nil {
				return fmt.Errorf("Slack alert failed: %v", err)
			}
		case "webhook":
			err := am.sendWebhookAlert(alert, analysis, channel)
			if err != nil {
				return fmt.Errorf("Webhook alert failed: %v", err)
			}
		}
	}

	return nil
}

// sendGitHubAlert sends an alert as a GitHub issue
func (am *AlertManager) sendGitHubAlert(alert RegressionAlert, analysis *RegressionAnalysis, channel NotificationChannel) error {
	// This would integrate with GitHub API to create issues
	// For now, just log the alert
	fmt.Printf("GitHub Alert: %s - %s (%s)\n", alert.Type, alert.BenchmarkName, alert.Severity)

	// In a real implementation, this would:
	// 1. Use GitHub API token from environment or config
	// 2. Create an issue with formatted content
	// 3. Add appropriate labels
	// 4. Assign to relevant team members

	return nil
}

// sendSlackAlert sends an alert to Slack
func (am *AlertManager) sendSlackAlert(alert RegressionAlert, analysis *RegressionAnalysis, channel NotificationChannel) error {
	webhookURL := channel.Config["webhook_url"]
	if webhookURL == "" {
		return fmt.Errorf("Slack webhook URL not configured")
	}

	// Format message for Slack
	message := am.formatSlackMessage(alert, analysis)

	payload := map[string]interface{}{
		"text": message,
		"attachments": []map[string]interface{}{
			{
				"color": am.getSlackColor(alert.Severity),
				"fields": []map[string]interface{}{
					{
						"title": "Benchmark",
						"value": alert.BenchmarkName,
						"short": true,
					},
					{
						"title": "Severity",
						"value": strings.ToUpper(alert.Severity),
						"short": true,
					},
				},
			},
		},
	}

	return am.sendWebhookPayload(webhookURL, payload)
}

// sendWebhookAlert sends a generic webhook alert
func (am *AlertManager) sendWebhookAlert(alert RegressionAlert, analysis *RegressionAnalysis, channel NotificationChannel) error {
	webhookURL := channel.Config["url"]
	if webhookURL == "" {
		return fmt.Errorf("Webhook URL not configured")
	}

	payload := map[string]interface{}{
		"alert":     alert,
		"analysis":  analysis,
		"timestamp": time.Now(),
	}

	return am.sendWebhookPayload(webhookURL, payload)
}

// sendSummaryAlert sends a summary of all alerts
func (am *AlertManager) sendSummaryAlert(analysis *RegressionAnalysis) error {
	// Create summary alert
	summaryAlert := RegressionAlert{
		Type:      "summary",
		Severity:  "major",
		Message:   am.formatSummaryMessage(analysis),
		Timestamp: time.Now(),
	}

	return am.sendAlert(summaryAlert, analysis)
}

// Helper methods

func (am *AlertManager) generateAlertID(alert RegressionAlert) string {
	return fmt.Sprintf("%s_%s_%s_%d",
		alert.Type, alert.BenchmarkName, alert.Severity, alert.Timestamp.Unix())
}

func (am *AlertManager) calculateAlertHash(alert RegressionAlert) string {
	// Simple hash for duplicate detection
	return fmt.Sprintf("%s_%s_%s", alert.Type, alert.BenchmarkName, alert.Severity)
}

func (am *AlertManager) isRateLimited(history *AlertHistory) bool {
	cutoff := time.Now().Add(-time.Hour)
	count := 0

	for _, alert := range history.Alerts {
		if alert.Timestamp.After(cutoff) {
			count++
		}
	}

	return count >= am.config.RateLimiting.MaxAlertsPerHour
}

func (am *AlertManager) formatSlackMessage(alert RegressionAlert, analysis *RegressionAnalysis) string {
	emoji := "⚠️"
	if alert.Severity == "critical" {
		emoji = "🚨"
	}

	return fmt.Sprintf("%s Performance Alert: %s\n%s", emoji, alert.BenchmarkName, alert.Message)
}

func (am *AlertManager) formatSummaryMessage(analysis *RegressionAnalysis) string {
	return fmt.Sprintf("Performance regression summary: %d total regressions (%d critical, %d major)",
		analysis.Summary.CriticalRegressions+analysis.Summary.MajorRegressions+analysis.Summary.MinorRegressions,
		analysis.Summary.CriticalRegressions,
		analysis.Summary.MajorRegressions)
}

func (am *AlertManager) getSlackColor(severity string) string {
	switch severity {
	case "critical":
		return "danger"
	case "major":
		return "warning"
	default:
		return "good"
	}
}

func (am *AlertManager) sendWebhookPayload(url string, payload interface{}) error {
	data, err := json.Marshal(payload)
	if err != nil {
		return err
	}

	resp, err := http.Post(url, "application/json", bytes.NewBuffer(data))
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("webhook failed with status %d: %s", resp.StatusCode, string(body))
	}

	return nil
}

func (am *AlertManager) loadAlertHistory() (*AlertHistory, error) {
	data, err := os.ReadFile(am.alertsFile)
	if err != nil {
		return nil, err
	}

	var history AlertHistory
	err = json.Unmarshal(data, &history)
	return &history, err
}

func (am *AlertManager) saveAlertHistory(history *AlertHistory) error {
	data, err := json.MarshalIndent(history, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(am.alertsFile, data, 0644)
}

func (am *AlertManager) cleanupAlertHistory(history *AlertHistory) {
	// Remove alerts older than 30 days
	cutoff := time.Now().AddDate(0, 0, -30)
	filtered := make([]SentAlert, 0)

	for _, alert := range history.Alerts {
		if alert.Timestamp.After(cutoff) {
			filtered = append(filtered, alert)
		}
	}

	history.Alerts = filtered
}
